# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-workshops',
                'doc_host': 'https://pnadelofficial.github.io',
                'git_url': 'https://github.com/pnadelofficial/nbdev-workshops',
                'lib_path': 'nbdev_workshops'},
  'syms': {'nbdev_workshops.core': {'nbdev_workshops.core.foo': ('core.html#foo', 'nbdev_workshops/core.py')}}}
